export const CHARACTERS = [
  {
    id: "beetle",
    name: "ヘラクレス",
    emoji: "🪲",
    tag: "スピード",
    desc: "まっすぐ速い。重くてぶつかり強い。必殺は角突きで相手を蹴散らす",
    color: 0x2a2410,
    accent: 0xc2a24a,
    maxSpeed: 28.4,
    accel: 15.5,
    handling: 1.72,
    weight: 1.25,
  },
  {
    id: "ladybug",
    name: "テントウ",
    emoji: "🐞",
    tag: "ハンドリング",
    desc: "曲がり上手。細い道が得意。必殺はてんとう舞いでコースの真ん中へ戻る",
    color: 0xd62828,
    accent: 0x1a120c,
    maxSpeed: 25.6,
    accel: 18.2,
    handling: 2.42,
    weight: 0.82,
  },
  {
    id: "bee",
    name: "ミツバチ",
    emoji: "🐝",
    tag: "加速",
    desc: "出足が速い。ハチミツと相性よし。必殺はみつばちジェットで一気に加速する",
    color: 0xf4d35e,
    accent: 0x1a120c,
    maxSpeed: 26.6,
    accel: 22.4,
    handling: 2.05,
    weight: 0.9,
  },
  {
    id: "hopper",
    name: "キリギリス",
    emoji: "🦗",
    tag: "ドリフト",
    desc: "ドリフトチャージが溜まりやすい。必殺は大ジャンプで天敵を飛び越える",
    color: 0x7a9a45,
    accent: 0xc4b07a,
    maxSpeed: 26.2,
    accel: 17.4,
    handling: 2.18,
    weight: 1.0,
    driftBonus: 1.25,
  },
];

export function getCharacter(id) {
  return CHARACTERS.find((c) => c.id === id) ?? CHARACTERS[0];
}
